version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1
workflows:
  build: 
    jobs:
      - cypress/run:
          command: npx cypress run --headless --config integrationFolder=cypress/specs
          yarn: true
