version: 2.1
orbs:
  cypress: cypress-io/cypress@1.25.1
workflows:
  build: 
    jobs:
      - cypress/run:
          name: 'API Tests' 
          install-command: yarn install --frozen-lockfile
          command: yarn cy:run
          yarn: true
